version: 1
disable_existing_loggers: false

formatters:
  json:
    format: "%(message)s"

handlers:
  stdout:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: json

root:
  level: INFO
  handlers: [stdout]

loggers:
  app:
    level: DEBUG
    handlers: [stdout]
    propagate: no

  uvicorn.access:
    level: INFO
    handlers: [stdout]
    propagate: no

  uvicorn.error:
    level: WARNING
    handlers: [stdout]
    propagate: no

  slowapi:
    level: INFO
    handlers: [stdout]
    propagate: no
